_format_version: "2.1"

services:
  - name: hello-example
    host: flask-app
    port: 5000
    protocol: http
    routes:
    - name: dummy-route
      paths:
        - /
  - name: service-app
    url: http://flask-app:5000/services
    routes:
    - name: service-route
      paths:
        - /services
        - /virtual-path
