_format_version: "3.0"
services:
- host: flask-app
  name: service-app
  port: 8000
  protocol: http
  routes:
  - name: service-route
    strip_path: false
    expression: 'http.path ^= "/services/" || http.path ^="/virtual-path"'
